### ISSUE TITLE
nlsJack will fail if the model was fitted using weighted least squares

### ISSUE THREAD

**Issue by mattiaciollaro** [aursiber/nlstools#5]
I suspect you might also need  something like
```
weights = weights[-z]
```
in the call to `update` here: https://github.com/aursiber/nlstools/blob/main/R/nlsJack.R#L11-L14

Changing line 13 to this would probably do the trick:

```
nls2 <- update(nls, data=data[-z,], weights=if (is.null(weights)) weights else weights[-z], start=as.list(coef(nls)));
```

**Comment by aursiber** [comment]
Thank you for the report.
Solved in 8f1089e93b1d6b780a418617e0bd796c54cd813d
