### ISSUE TITLE
Resampling when nls object includes a categorical predictor

### ISSUE THREAD

**Issue by averill-murray** [aursiber/nlstools#6]
Do nlsJack and nlsBoot work if the nls object includes a categorical predictor? I get the following error (Asym and k are the only parameters in the model, both with "Sex" as a categorical predictor:

Error in nls(formula = vonB_exp, data = data[-z, ], start = as.list(coef(nls)),  : 
  parameters without starting value in 'data': Asym, k

Thanks!

**Comment by Florent-Baty** [comment]
Hello,

Thank you very much for reporting this issue. Could you possibly send me
more details about the data and models you fitted so that I can try to
reproduce and possibly fix this problem?

Many thanks in advance,

Florent

**Comment by averill-murray** [comment]
[growth.csv](https://github.com/aursiber/nlstools/files/14196395/growth.csv)
I attached the data file. Here is a series of code that leads to the error:

growth$Sex <- as.factor(growth$Sex)
levels(growth$Sex)[levels(growth$Sex) == "U1"] <- "M"
levels(growth$Sex)[levels(growth$Sex) == "U2"] <- "F"
vonB_exp1 <- as.formula(MCL2 ~ Asym[Sex] - (Asym[Sex]-MCL1)*exp(-k[Sex]*YearInt))
vonB.nls1 <- nls(vonB_exp1, data = growth, start = list(Asym = c(285, 285), k = c(0.07, 0.07)))
nlsJack(vonB.nls1)
nlsBoot(vonB.nls1) #Gives a different error that may be more related to the model: "Procedure aborted: the fit only converged in 1 % during bootstrapping"

I get the same errors with model that only includes Asym[Sex] (dropping the extra k value in the nls call).  Both functions work without the Sex factor.
Roy

**Comment by Florent-Baty** [comment]
Hello Roy,

Many thanks again for reporting the issue with nlstools. Indeed the
function nlsJack and nlsBoot does not handle the cases when we have
categorical variables (problem with the names of the starting values).

As a temporary workaround, please use the following updated functions (see
below). I'll fix the bug in a new release of the package soon.

Kind regards,

Florent



nlsJack <- function (nls)
{
    if (!inherits(nls, "nls"))
        stop("Use only with 'nls' objects")
    c1 <- nls$call
    data <- eval(c1$data, sys.frame(0))
    start0 <- eval(c1$start, sys.frame(0))
    c1$start <- as.list(coef(nls))
    nl <- nrow(data)
    np <- length(coef(nls))
    l1 <- lapply(1:nl, function(z) {
        if (!is.null(weights(nls))) {
            nls2 <- update(nls, data = data[-z, ], weights =
weights(nls)[-z],
                start = start0)
        }
        else {
            nls2 <- update(nls, data = data[-z, ], start = start0)
        }
        return(list(coef = coef(nls2), sigma = summary(nls2)$sigma,
            rss = sum(residuals(nls2)^2), dfb = abs(coef(nls2) -
                coef(nls))/(summary(nls)$parameters[, 2])))
    })
    tabjack <- t(sapply(l1, function(z) z$coef))
    rsejack <- sapply(l1, function(z) z$sigma)
    rssjack <- sapply(l1, function(z) z$rss)
    dfb <- t(sapply(l1, function(z) z$dfb))
    reldif <- apply(tabjack, 1, function(x) 100 * abs(x -
coef(nls))/coef(nls))
    pseudo <- t(apply((nl - 1) * tabjack, 1, function(z) nl *
        coef(nls) - z))
    estijack <- cbind.data.frame(Estimates = colSums(pseudo)/nl,
        Bias = coef(nls) - colSums(pseudo)/nl)
    sum1 <- crossprod(t(t(pseudo) - estijack$Estimates))
    varjack <- (1/(nl * (nl - 1))) * sum1
    student95 <- qt(0.975, df = nl - np)
    ICjack <- cbind.data.frame(Esti = estijack$Estimates, Low =
estijack$Estimates -
        student95 * sqrt(diag(varjack)), Up = estijack$Estimates +
        student95 * sqrt(diag(varjack)))
    listjack <- list(estijack = estijack, coefjack = tabjack,
        reldif = reldif, rse = rsejack, rss = rssjack, dfb = dfb,
        jackCI = ICjack)
    class(listjack) <- "nlsJack"
    return(listjack)
}

nlsBoot <- function (nls, niter = 999)
{
    if (!inherits(nls, "nls"))
        stop("Use only with 'nls' objects")
    data2 <- eval(nls$data, sys.frame(0))
    start0 <- eval(nls$call$start, sys.frame(0))
    fitted1 <- fitted(nls)
    resid1 <- resid(nls)
    var1 <- all.vars(formula(nls)[[2]])
    l1 <- lapply(1:niter, function(i) {
        data2[, var1] <- fitted1 + sample(scale(resid1, scale = FALSE),
            replace = TRUE)
        nls2 <- try(update(nls, start = start0, data = data2),
            silent = TRUE)
        if (inherits(nls2, "nls"))
            return(list(coef = coef(nls2), rse = summary(nls2)$sigma))
    })
    if (sum(sapply(l1, is.null)) > niter/2)
        stop(paste("Procedure aborted: the fit only converged in",
            round(sum(sapply(l1, is.null))/niter), "% during
bootstrapping"))
    tabboot <- sapply(l1[!sapply(l1, is.null)], function(z) z$coef)
    rseboot <- sapply(l1[!sapply(l1, is.null)], function(z) z$rse)
    recapboot <- t(apply(tabboot, 1, quantile, c(0.5, 0.025,
        0.975)))
    colnames(recapboot) <- c("Median", "2.5%", "97.5%")
    estiboot <- t(apply(tabboot, 1, function(z) c(mean(z), sd(z))))
    colnames(estiboot) <- c("Estimate", "Std. error")
    serr <- sum(sapply(l1, is.null))
    if (serr > 0)
        warning(paste("The fit did not converge", serr, "times during
bootstrapping"))
    listboot <- list(coefboot = t(tabboot), rse = rseboot, bootCI =
recapboot,
        estiboot = estiboot, nls = nls)
    class(listboot) <- "nlsBoot"
    return(listboot)
}

**Comment by averill-murray** [comment]
Thanks!

**Comment by Florent-Baty** [comment]
A new package release is now available on CRAN and github including a bug fix.
